### ISSUE TITLE
First commit review

### ISSUE THREAD

**Issue by objectuser** [spreedly/rheostat#1]
@duff @dtykocki 

I extracted the module from S3PO into this repo.

There might be a better way to approach this, but wanted to get some (more) feedback. It should do the same thing as what we talked about yesterday.

**Comment by duff** [comment]
Looks neat and useful to me.

**Comment by objectuser** [comment]
Cool, I'm going to try to incorporate it in S3PO.

**Comment by objectuser** [comment]
One "gotcha" with the compile time wiring of the adapter is that the dependency need to be cleaned/recompiled if the config changes.

I could either leave it or use `Application.get_env(:rheostat, :adapter, Rheostat.Adapter.Metrix)` for every call.
